/**
 * data.js — Модуль данных меню ресторана.
 * Содержит массив объектов с блюдами трёх категорий:
 * hot (горячее), salads (салаты), desserts (десерты).
 *
 * Каждое блюдо: { id, category, name, desc, price, calories, weight, emoji, tags: [] }
 * tags: ['popular', 'vegetarian', 'spicy']
 */

export const menuItems = [
  // ─── ГОРЯЧЕЕ ──────────────────────────────────────────────
  {
    id: 1,
    category: 'hot',
    name: 'Утиная грудка',
    desc: 'Карамелизованная утиная грудка с соусом из красного вина, картофельным пюре и тимьяном.',
    price: 540,
    calories: 620,
    weight: 280,
    emoji: '🍗',
    bgColor: '#fef3e2',
    tags: ['popular'],
  },
  {
    id: 2,
    category: 'hot',
    name: 'Паста Карбонара',
    desc: 'Классическая итальянская паста с беконом, яйцом, пармезаном и свежемолотым перцем.',
    price: 380,
    calories: 740,
    weight: 320,
    emoji: '🍝',
    bgColor: '#fff8e7',
    tags: ['popular'],
  },
  {
    id: 3,
    category: 'hot',
    name: 'Стейк Рибай',
    desc: 'Говяжий рибай на углях, степень прожарки medium-rare, с соусом чимичурри и овощами гриль.',
    price: 890,
    calories: 820,
    weight: 300,
    emoji: '🥩',
    bgColor: '#fde9e9',
    tags: ['popular'],
  },
  {
    id: 4,
    category: 'hot',
    name: 'Лосось на пару',
    desc: 'Нежный филе лосося, приготовленный на пару, с лимонным маслом, киноа и спаржей.',
    price: 620,
    calories: 450,
    weight: 260,
    emoji: '🐟',
    bgColor: '#e8f4fb',
    tags: ['popular'],
  },
  {
    id: 5,
    category: 'hot',
    name: 'Ризотто с грибами',
    desc: 'Кремовое ризотто с лесными грибами, трюфельным маслом и пармезаном Реджано.',
    price: 420,
    calories: 580,
    weight: 300,
    emoji: '🍚',
    bgColor: '#f5f0e8',
    tags: ['vegetarian'],
  },
  {
    id: 6,
    category: 'hot',
    name: 'Острые креветки',
    desc: 'Тигровые креветки в остром соусе чили-чеснок на чугунной сковороде с хлебом на гриле.',
    price: 560,
    calories: 390,
    weight: 250,
    emoji: '🍤',
    bgColor: '#fde8e8',
    tags: ['spicy'],
  },

  // ─── САЛАТЫ ───────────────────────────────────────────────
  {
    id: 7,
    category: 'salads',
    name: 'Нисуаз',
    desc: 'Классический французский салат с тунцом, яйцом, зелёной фасолью, оливками и анчоусами.',
    price: 340,
    calories: 310,
    weight: 280,
    emoji: '🥗',
    bgColor: '#e8f5e9',
    tags: ['popular'],
  },
  {
    id: 8,
    category: 'salads',
    name: 'Цезарь с курицей',
    desc: 'Хрустящий ромэн, куриная грудка гриль, крутоны, соус Цезарь и стружка пармезана.',
    price: 290,
    calories: 420,
    weight: 260,
    emoji: '🥬',
    bgColor: '#f0f8f0',
    tags: ['popular'],
  },
  {
    id: 9,
    category: 'salads',
    name: 'Капрезе',
    desc: 'Томаты семейства Heirloom, моцарелла буффало, свежий базилик, соус из бальзамика и оливковое масло.',
    price: 320,
    calories: 260,
    weight: 230,
    emoji: '🍅',
    bgColor: '#fff0ef',
    tags: ['vegetarian'],
  },
  {
    id: 10,
    category: 'salads',
    name: 'Греческий',
    desc: 'Огурцы, томаты, перец, лук, маслины Каламата и сыр фета с орегано и оливковым маслом.',
    price: 270,
    calories: 220,
    weight: 250,
    emoji: '🫒',
    bgColor: '#f0f4ff',
    tags: ['vegetarian'],
  },
  {
    id: 11,
    category: 'salads',
    name: 'Острый тайский',
    desc: 'Манго, папайя, перец чили, арахис, кинза и рисовая лапша в кисло-сладком соусе Nam Jim.',
    price: 310,
    calories: 280,
    weight: 240,
    emoji: '🌮',
    bgColor: '#fef9e0',
    tags: ['spicy', 'vegetarian'],
  },
  {
    id: 12,
    category: 'salads',
    name: 'Руккола с грушей',
    desc: 'Нежная руккола, карамелизованная груша, грецкие орехи, горгонзола и медовая заправка.',
    price: 300,
    calories: 340,
    weight: 210,
    emoji: '🍐',
    bgColor: '#f0faf3',
    tags: ['vegetarian'],
  },

  // ─── ДЕСЕРТЫ ──────────────────────────────────────────────
  {
    id: 13,
    category: 'desserts',
    name: 'Тирамису',
    desc: 'Классический итальянский тирамису с маскарпоне, эспрессо и печеньем Савоярди.',
    price: 280,
    calories: 480,
    weight: 160,
    emoji: '🍰',
    bgColor: '#fdf0e0',
    tags: ['popular'],
  },
  {
    id: 14,
    category: 'desserts',
    name: 'Крем-брюле',
    desc: 'Нежная ванильная запеканка с хрустящей карамельной корочкой и свежей малиной.',
    price: 250,
    calories: 380,
    weight: 150,
    emoji: '🍮',
    bgColor: '#fff8ea',
    tags: ['popular'],
  },
  {
    id: 15,
    category: 'desserts',
    name: 'Шоколадный фондан',
    desc: 'Тёплый шоколадный кекс с жидкой начинкой, ванильным мороженым и малиновым соусом.',
    price: 300,
    calories: 560,
    weight: 180,
    emoji: '🍫',
    bgColor: '#f5ebe0',
    tags: ['popular'],
  },
  {
    id: 16,
    category: 'desserts',
    name: 'Панна котта',
    desc: 'Итальянский сливочный десерт с ванилью, соусом из лесных ягод и мятой.',
    price: 240,
    calories: 320,
    weight: 140,
    emoji: '🍨',
    bgColor: '#fdf3fb',
    tags: ['vegetarian'],
  },
  {
    id: 17,
    category: 'desserts',
    name: 'Баклава',
    desc: 'Хрустящее слоёное тесто с фисташками и грецкими орехами, пропитанное мёдом и розовой водой.',
    price: 220,
    calories: 440,
    weight: 130,
    emoji: '🧁',
    bgColor: '#fef7e0',
    tags: ['vegetarian'],
  },
  {
    id: 18,
    category: 'desserts',
    name: 'Сорбет манго',
    desc: 'Освежающий сорбет из спелого манго, сока лайма и листьев мяты. Без глютена.',
    price: 190,
    calories: 180,
    weight: 120,
    emoji: '🍧',
    bgColor: '#fffbea',
    tags: ['vegetarian'],
  },
];
